### ISSUE TITLE
Webfrontend: Filter for Source and Mode show blank filter result if applied as first and only filter. [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by lwiniwar** [3dgeo-heidelberg/pytreedb#37]
The original issue

	Id: 31
	Title: Webfrontend: Filter for Source and Mode show blank filter result if applied as first and only filter.

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.gistools.geog.uni-heidelberg.de/giscience/3DGeo/pytreedb/-/issues/31

**Comment by annachiu7** [comment]
We should probably discuss about how to approach the json-downloading performance problem if the users are requesting for a lot of files e.g. >300, because it's indeed a lot for the client side to process (truncating all results into one large json & reading laz file downloading info from each result...)

**Comment by annachiu7** [comment]
Source of problem found: there's a mini error in the dataset. But good that we are now aware of some performance problem
