### ISSUE TITLE
Webfrontend: Interface adapt for larger datasets

### ISSUE THREAD

**Issue by annachiu7** [3dgeo-heidelberg/pytreedb#68]

**Comment by bhoefle-3dgeo** [comment]
Problem: If there is many trees (>200k) in the database like in the example here [here](https://github.com/3dgeo-heidelberg/pytreedb/blob/vienna_test/examples/example_load_trees_from_ogc_wfs.py), the web map is not working properly anymore because it seems to load all trees into the web map or in the background. If one applies search filters and reduce the number of trees, it works again.

Tests: Please test with the large database. 

Possible Solution: One needs to avoid loading a max. no. of trees to display. Maybe this can be combined efficiently with the collapsed marker solution. Anyways it must be avoided that all trees are loaded if you imagine that a database could contain 100M or more trees, which is not feasible to show on the map.

**Comment by annachiu7** [comment]
The lag mainly comes from adding each tree to the cluster. So I just set a maximum threshold of the number of markers that can be shown on the map. The users will get an pop-up if they choose to display all results but the max. is exceeded.
